### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by bentotten** [wwoods/job_stream#2]
Unable to install job_stream

From inside an activated conda environment, this error occurs:
```
Collecting job_stream
  Using cached job_stream-0.1.32.tar.gz (385 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-xttc0yzd/job-stream_e6fbd1a0949743d88853f85759fef912/setup.py", line 48, in <module>
          mpiFlagsCompile = checkedRun([ mpiCompiler, "--showme:compile" ])
        File "/tmp/pip-install-xttc0yzd/job-stream_e6fbd1a0949743d88853f85759fef912/setup.py", line 46, in checkedRun
          raise Exception("Program failed with {}: {}".format(r, args))
      Exception: Program failed with 127: ['mpicxx', '--showme:compile']
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Outside of a conda env, there are several pages of error that conclude with:
```
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-s9mj7xu5/job-stream/setup.py'"'"'; __file__='"'"'/tmp/pip-install-s9mj7xu5/job-stream/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-17675lnq/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /u/<un>/.local/include/python3.8/job-stream Check the logs for full command output.
```

Have tried a couple different methods with pip, but no luck

**Comment by wwoods** [comment]
Hey @bentotten -- This library isn't really maintained, and I don't currently have time to look into this error. It looks like the MPI compiler may have had a breaking change that needs to be fixed in one of the Cpp files.

I would recommend [Ray](https://www.ray.io/) or [Dask](https://dask.org/) for your distributed Python needs these days.

**Comment by bentotten** [comment]
@wwoods good to know, thank you for your recommendations - I'll close the issue
